#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := shift_register.cpp layer.cpp            cube.cpp line.cpp               rectangle.cpp rotating_plane.cpp alphabet.cpp pulsing_cube.cpp kitt.cpp

# header files in this project
HEADERS := shift_register.hpp layer.hpp vector.hpp cube.hpp line.hpp animation.hpp rectangle.hpp rotating_plane.hpp alphabet.hpp pulsing_cube.hpp kitt.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due